const fs = require('fs');

const amenities = ["2 Fiberglass platforms","Compass","Electric bilge pump","Roller bar with awning and navigation lights","Steering wheel -Fiberglass winch","Storage compartments with USB sockets","Shower","Sun cushions","Bimini","Outdoor shower","External table","External speakers","Teak deck","Bathing Platform","Bathing ladder","USB socket","Electric windlass","GPS","Depth sounder","VHF","Guides & Maps","Fridge","Freezer","Private Skipper","Professional Sailor/Guide","Welcome Drinks","Towels","Gas cookers","Shore connection 220 V","VHF Radio","Hi-Fi system","Cockpit outside shower","First aid kit","Teak cockpit","Fish finder","Wi-Fi Internet","Mooring ropes","TV","Main anchor","Electric toilet","Generator","Horseshoe lifebuoy","Kitchen utensils","Liferaft","Set of tools","Life jackets","Cockpit table","Oven","Autopilot","Gas bottle","Spare anchor","Navigation charts","Hot water","Signal rockets and torches","Bed linen","Logge/Lot/Speed","Divider nautic chart","Hand-held compass","Fire extinguisher","Harbour guides","Battery Charger","Life belts","Electric Anchor Windlass","Emergency tiller","GPS chart plotter","Hydraulic gangway","Dinghy","Fenders"];

const translations = {
  en: amenities.reduce((acc, item) => ({ ...acc, [item]: item }), {}),
  
  de: {
    "2 Fiberglass platforms": "2 Glasfaser-Plattformen",
    "Compass": "Kompass",
    "Electric bilge pump": "Elektrische Bilgenpumpe",
    "Roller bar with awning and navigation lights": "Überrollbügel mit Markise und Navigationslichtern",
    "Steering wheel -Fiberglass winch": "Lenkrad - Glasfaserwinde",
    "Storage compartments with USB sockets": "Staufächer mit USB-Steckdosen",
    "Shower": "Dusche",
    "Sun cushions": "Sonnenkissen",
    "Bimini": "Bimini",
    "Outdoor shower": "Außendusche",
    "External table": "Außentisch",
    "External speakers": "Außenlautsprecher",
    "Teak deck": "Teakdeck",
    "Bathing Platform": "Badeplattform",
    "Bathing ladder": "Badeleiter",
    "USB socket": "USB-Steckdose",
    "Electric windlass": "Elektrische Ankerwinde",
    "GPS": "GPS",
    "Depth sounder": "Echolot",
    "VHF": "UKW",
    "Guides & Maps": "Reiseführer & Karten",
    "Fridge": "Kühlschrank",
    "Freezer": "Gefrierschrank",
    "Private Skipper": "Privater Skipper",
    "Professional Sailor/Guide": "Professioneller Segler/Guide",
    "Welcome Drinks": "Begrüßungsgetränke",
    "Towels": "Handtücher",
    "Gas cookers": "Gaskocher",
    "Shore connection 220 V": "Landanschluss 220 V",
    "VHF Radio": "UKW-Funk",
    "Hi-Fi system": "Hi-Fi Anlage",
    "Cockpit outside shower": "Cockpit-Außendusche",
    "First aid kit": "Erste-Hilfe-Kasten",
    "Teak cockpit": "Teak-Cockpit",
    "Fish finder": "Fischfinder",
    "Wi-Fi Internet": "WLAN",
    "Mooring ropes": "Festmacherleinen",
    "TV": "Fernseher",
    "Main anchor": "Hauptanker",
    "Electric toilet": "Elektrische Toilette",
    "Generator": "Generator",
    "Horseshoe lifebuoy": "Rettungsring",
    "Kitchen utensils": "Küchenutensilien",
    "Liferaft": "Rettungsinsel",
    "Set of tools": "Werkzeugkasten",
    "Life jackets": "Rettungswesten",
    "Cockpit table": "Cockpittisch",
    "Oven": "Ofen",
    "Autopilot": "Autopilot",
    "Gas bottle": "Gasflasche",
    "Spare anchor": "Ersatzanker",
    "Navigation charts": "Seekarten",
    "Hot water": "Warmwasser",
    "Signal rockets and torches": "Signalraketen und Fackeln",
    "Bed linen": "Bettwäsche",
    "Logge/Lot/Speed": "Logge/Lot/Geschwindigkeit",
    "Divider nautic chart": "Nautischer Zirkel",
    "Hand-held compass": "Peilkompass",
    "Fire extinguisher": "Feuerlöscher",
    "Harbour guides": "Hafenhandbücher",
    "Battery Charger": "Batterieladegerät",
    "Life belts": "Rettungsgurte",
    "Electric Anchor Windlass": "Elektrische Ankerwinde",
    "Emergency tiller": "Notpinne",
    "GPS chart plotter": "GPS-Kartenplotter",
    "Hydraulic gangway": "Hydraulische Gangway",
    "Dinghy": "Beiboot",
    "Fenders": "Fender"
  },

  hr: {
    "2 Fiberglass platforms": "2 stakloplastične platforme",
    "Compass": "Kompas",
    "Electric bilge pump": "Električna kaljužna pumpa",
    "Roller bar with awning and navigation lights": "Roll bar s tendom i navigacijskim svjetlima",
    "Steering wheel -Fiberglass winch": "Upravljač - stakloplastično vitlo",
    "Storage compartments with USB sockets": "Pretinci s USB utičnicama",
    "Shower": "Tuš",
    "Sun cushions": "Jastuci za sunčanje",
    "Bimini": "Bimini tenda",
    "Outdoor shower": "Vanjski tuš",
    "External table": "Vanjski stol",
    "External speakers": "Vanjski zvučnici",
    "Teak deck": "Paluba od tikovine",
    "Bathing Platform": "Platforma za kupanje",
    "Bathing ladder": "Ljestve za kupanje",
    "USB socket": "USB utičnica",
    "Electric windlass": "Električno vitlo",
    "GPS": "GPS",
    "Depth sounder": "Dubinomjer",
    "VHF": "VHF",
    "Guides & Maps": "Vodiči i karte",
    "Fridge": "Hladnjak",
    "Freezer": "Zamrzivač",
    "Private Skipper": "Privatni skiper",
    "Professional Sailor/Guide": "Profesionalni mornar/vodič",
    "Welcome Drinks": "Piće dobrodošlice",
    "Towels": "Ručnici",
    "Gas cookers": "Plinsko kuhalo",
    "Shore connection 220 V": "Obalni priključak 220 V",
    "VHF Radio": "VHF radio",
    "Hi-Fi system": "Hi-Fi sustav",
    "Cockpit outside shower": "Vanjski tuš u kokpitu",
    "First aid kit": "Kutija prve pomoći",
    "Teak cockpit": "Kokpit od tikovine",
    "Fish finder": "Riblji sonar",
    "Wi-Fi Internet": "Wi-Fi",
    "Mooring ropes": "Konopi za vezanje",
    "TV": "TV",
    "Main anchor": "Glavno sidro",
    "Electric toilet": "Električni WC",
    "Generator": "Generator",
    "Horseshoe lifebuoy": "Pojas za spašavanje (potkova)",
    "Kitchen utensils": "Kuhinjski pribor",
    "Liferaft": "Splav za spašavanje",
    "Set of tools": "Komplet alata",
    "Life jackets": "Prsluci za spašavanje",
    "Cockpit table": "Stol u kokpitu",
    "Oven": "Pećnica",
    "Autopilot": "Autopilot",
    "Gas bottle": "Plinska boca",
    "Spare anchor": "Pomoćno sidro",
    "Navigation charts": "Navigacijske karte",
    "Hot water": "Topla voda",
    "Signal rockets and torches": "Signalne rakete i baklje",
    "Bed linen": "Posteljina",
    "Logge/Lot/Speed": "Brzinomjer/Dubinomjer",
    "Divider nautic chart": "Nautički šestar",
    "Hand-held compass": "Ručni kompas",
    "Fire extinguisher": "Aparat za gašenje požara",
    "Harbour guides": "Lučki vodiči",
    "Battery Charger": "Punjač baterija",
    "Life belts": "Pojasevi za spašavanje",
    "Electric Anchor Windlass": "Električno sidreno vitlo",
    "Emergency tiller": "Pomoćno rudo",
    "GPS chart plotter": "GPS ploter",
    "Hydraulic gangway": "Hidraulična pasarela",
    "Dinghy": "Gumenjak",
    "Fenders": "Bokobrani"
  },

  it: {
    "2 Fiberglass platforms": "2 piattaforme in vetroresina",
    "Compass": "Bussola",
    "Electric bilge pump": "Pompa di sentina elettrica",
    "Roller bar with awning and navigation lights": "Roll bar con tendalino e luci di navigazione",
    "Steering wheel -Fiberglass winch": "Volante - verricello in vetroresina",
    "Storage compartments with USB sockets": "Vani portaoggetti con prese USB",
    "Shower": "Doccia",
    "Sun cushions": "Cuscini prendisole",
    "Bimini": "Tendalino parasole",
    "Outdoor shower": "Doccia esterna",
    "External table": "Tavolo esterno",
    "External speakers": "Altoparlanti esterni",
    "Teak deck": "Ponte in teak",
    "Bathing Platform": "Piattaforma da bagno",
    "Bathing ladder": "Scaletta da bagno",
    "USB socket": "Presa USB",
    "Electric windlass": "Verricello elettrico",
    "GPS": "GPS",
    "Depth sounder": "Ecoscandaglio",
    "VHF": "VHF",
    "Guides & Maps": "Guide e mappe",
    "Fridge": "Frigorifero",
    "Freezer": "Congelatore",
    "Private Skipper": "Skipper privato",
    "Professional Sailor/Guide": "Marinaio/Guida professionista",
    "Welcome Drinks": "Drink di benvenuto",
    "Towels": "Asciugamani",
    "Gas cookers": "Fornelli a gas",
    "Shore connection 220 V": "Presa banchina 220 V",
    "VHF Radio": "Radio VHF",
    "Hi-Fi system": "Impianto Hi-Fi",
    "Cockpit outside shower": "Doccia esterna in pozzetto",
    "First aid kit": "Kit di pronto soccorso",
    "Teak cockpit": "Pozzetto in teak",
    "Fish finder": "Ecoscandaglio per pesci",
    "Wi-Fi Internet": "Wi-Fi",
    "Mooring ropes": "Corde d'ormeggio",
    "TV": "TV",
    "Main anchor": "Ancora principale",
    "Electric toilet": "WC elettrico",
    "Generator": "Generatore",
    "Horseshoe lifebuoy": "Salvagente a ferro di cavallo",
    "Kitchen utensils": "Utensili da cucina",
    "Liferaft": "Zattera di salvataggio",
    "Set of tools": "Cassetta degli attrezzi",
    "Life jackets": "Giacche di salvataggio",
    "Cockpit table": "Tavolo nel pozzetto",
    "Oven": "Forno",
    "Autopilot": "Pilota automatico",
    "Gas bottle": "Bombola del gas",
    "Spare anchor": "Ancora di rispetto",
    "Navigation charts": "Carte nautiche",
    "Hot water": "Acqua calda",
    "Signal rockets and torches": "Razzi di segnalazione",
    "Bed linen": "Biancheria da letto",
    "Logge/Lot/Speed": "Solcometro/Ecoscandaglio",
    "Divider nautic chart": "Compasso nautico",
    "Hand-held compass": "Bussola da rilevamento",
    "Fire extinguisher": "Estintore",
    "Harbour guides": "Portolani",
    "Battery Charger": "Caricabatterie",
    "Life belts": "Cinture di sicurezza",
    "Electric Anchor Windlass": "Salpa ancora elettrico",
    "Emergency tiller": "Barra di rispetto",
    "GPS chart plotter": "GPS chart plotter",
    "Hydraulic gangway": "Passerella idraulica",
    "Dinghy": "Tender",
    "Fenders": "Parabordi"
  },

  nl: {
    "2 Fiberglass platforms": "2 glasvezel platformen",
    "Compass": "Kompas",
    "Electric bilge pump": "Elektrische lenspomp",
    "Roller bar with awning and navigation lights": "Beugel met zonnetent en navigatieverlichting",
    "Steering wheel -Fiberglass winch": "Stuurwiel - glasvezel lier",
    "Storage compartments with USB sockets": "Opbergvakken met USB",
    "Shower": "Douche",
    "Sun cushions": "Zonkussens",
    "Bimini": "Bimini tops",
    "Outdoor shower": "Buitendouche",
    "External table": "Buitentafel",
    "External speakers": "Buitenspeakers",
    "Teak deck": "Teakdek",
    "Bathing Platform": "Zwemplatform",
    "Bathing ladder": "Zwemladder",
    "USB socket": "USB-aansluiting",
    "Electric windlass": "Elektrische ankerlier",
    "GPS": "GPS",
    "Depth sounder": "Dieptemeter",
    "VHF": "Marifoon",
    "Guides & Maps": "Gidsen en kaarten",
    "Fridge": "Koelkast",
    "Freezer": "Vriezer",
    "Private Skipper": "Privé schipper",
    "Professional Sailor/Guide": "Professionele zeiler/gids",
    "Welcome Drinks": "Welkomstdrankjes",
    "Towels": "Handdoeken",
    "Gas cookers": "Gaskookstellen",
    "Shore connection 220 V": "Walstroomaansluiting 220 V",
    "VHF Radio": "VHF-radio",
    "Hi-Fi system": "HiFi systeem",
    "Cockpit outside shower": "Buitendouche kuip",
    "First aid kit": "EHBO-doos",
    "Teak cockpit": "Teak kuip",
    "Fish finder": "Visvinder",
    "Wi-Fi Internet": "Wi-Fi",
    "Mooring ropes": "Landvasten",
    "TV": "TV",
    "Main anchor": "Hoofdanker",
    "Electric toilet": "Elektrisch toilet",
    "Generator": "Generator",
    "Horseshoe lifebuoy": "Reddingsring",
    "Kitchen utensils": "Keukengerei",
    "Liferaft": "Reddingsvlot",
    "Set of tools": "Gereedschapsset",
    "Life jackets": "Reddingsvesten",
    "Cockpit table": "Kuiptafel",
    "Oven": "Oven",
    "Autopilot": "Stuurautomaat",
    "Gas bottle": "Gasfles",
    "Spare anchor": "Reserveanker",
    "Navigation charts": "Navigatiekaarten",
    "Hot water": "Warm water",
    "Signal rockets and torches": "Noodsignalen en fakkels",
    "Bed linen": "Beddengoed",
    "Logge/Lot/Speed": "Snelheidsmeter/Dieptemeter",
    "Divider nautic chart": "Navigatiepasser",
    "Hand-held compass": "Peilkompas",
    "Fire extinguisher": "Brandblusser",
    "Harbour guides": "Havengidsen",
    "Battery Charger": "Acculader",
    "Life belts": "Reddingslijnen",
    "Electric Anchor Windlass": "Elektrische ankerlier",
    "Emergency tiller": "Noodhelmstok",
    "GPS chart plotter": "GPS kaartplotter",
    "Hydraulic gangway": "Hydraulische loopplank",
    "Dinghy": "Bijboot",
    "Fenders": "Stootwillen"
  },

  sl: {
    "2 Fiberglass platforms": "2 platformi iz steklenih vlaken",
    "Compass": "Kompas",
    "Electric bilge pump": "Električna kalužna črpalka",
    "Roller bar with awning and navigation lights": "Mavričen drog s tendo in navigacijskimi lučmi",
    "Steering wheel -Fiberglass winch": "Volan - vitel iz steklenih vlaken",
    "Storage compartments with USB sockets": "Predali z USB vtičnicami",
    "Shower": "Tuš",
    "Sun cushions": "Blazine za sončenje",
    "Bimini": "Bimini tenda",
    "Outdoor shower": "Zunanji tuš",
    "External table": "Zunanja miza",
    "External speakers": "Zunanji zvočniki",
    "Teak deck": "Tikov paluba",
    "Bathing Platform": "Kopalna ploščad",
    "Bathing ladder": "Kopalna lestev",
    "USB socket": "USB vtičnica",
    "Electric windlass": "Električni vitel",
    "GPS": "GPS",
    "Depth sounder": "Globinoměr",
    "VHF": "VHF",
    "Guides & Maps": "Vodiči in karte",
    "Fridge": "Hladilnik",
    "Freezer": "Zamrzovalnik",
    "Private Skipper": "Zasebni skipper",
    "Professional Sailor/Guide": "Profesionalni mornar/vodič",
    "Welcome Drinks": "Pijače dobrodošlice",
    "Towels": "Brisače",
    "Gas cookers": "Plinski kuhalnik",
    "Shore connection 220 V": "Obalni priključek 220 V",
    "VHF Radio": "VHF radijska postaja",
    "Hi-Fi system": "Hi-Fi sistem",
    "Cockpit outside shower": "Zunanji tuš v kokpitu",
    "First aid kit": "Komplet prve pomoči",
    "Teak cockpit": "Tikov kokpit",
    "Fish finder": "Iskalnik rib",
    "Wi-Fi Internet": "Wi-Fi",
    "Mooring ropes": "Vrvi za privez",
    "TV": "TV",
    "Main anchor": "Glavno sidro",
    "Electric toilet": "Električni WC",
    "Generator": "Generator",
    "Horseshoe lifebuoy": "Reševalni obroč (podkev)",
    "Kitchen utensils": "Kuhinjski pripomočki",
    "Liferaft": "Rešilna splav",
    "Set of tools": "Komplet orodja",
    "Life jackets": "Rešilni jopiči",
    "Cockpit table": "Miza v kokpitu",
    "Oven": "Pečica",
    "Autopilot": "Avtopilot",
    "Gas bottle": "Plinska jeklenka",
    "Spare anchor": "Rezervno sidro",
    "Navigation charts": "Navigacijske karte",
    "Hot water": "Topla voda",
    "Signal rockets and torches": "Signalne rakete in bakle",
    "Bed linen": "Posteljnina",
    "Logge/Lot/Speed": "Brzinomer/Globinomer",
    "Divider nautic chart": "Navtični šestilo",
    "Hand-held compass": "Ročni kompas",
    "Fire extinguisher": "Gasilni aparat",
    "Harbour guides": "Pristaniški vodiči",
    "Battery Charger": "Polnilec baterij",
    "Life belts": "Reševalni pasovi",
    "Electric Anchor Windlass": "Električni sidrni vitel",
    "Emergency tiller": "Zasilno krmilo",
    "GPS chart plotter": "GPS ploter",
    "Hydraulic gangway": "Hidravlična pasarela",
    "Dinghy": "Gumenjak",
    "Fenders": "Bokobrani"
  }
};

const mapLang = { en: "en", hr: "hr", de: "de", it: "it", nl: "nl", sl: "sl" };

Object.entries(mapLang).forEach(([lang, fileCode]) => {
  const file = `src/locales/${fileCode}UI.ts`;
  let content = fs.readFileSync(file, 'utf8');
  let langData = translations[lang];
  let jsonString = JSON.stringify(langData).slice(1, -1); // remove outer {}
  let replacementStr = "amenities: {" + jsonString + "},\n    boats:";
  content = content.replace(/boats:/, replacementStr);
  fs.writeFileSync(file, content);
});
console.log('done');
